name: Deploy static content to GitHub Pages

run-name: ${{ github.actor }} deploying ${{ github.repository_id }} to GitHub Pages

on:
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy_github_pages:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Information
      - name: Workflow Information
        run: |
          echo "==== Repository Information ===="
          echo "github.repository: ${{ github.repository }}"
          echo "github.repository_owner: ${{ github.repository_owner }}"
          echo "github.repository_id: ${{ github.repository_id }}"
          echo "github.repository_url: ${{ github.repository_url }}"

          echo "==== Workflow Run Information ===="
          echo "github.workflow: ${{ github.workflow }}"
          echo "github.job: ${{ github.job }}"
          echo "github.run_id: ${{ github.run_id }}"
          echo "github.run_number: ${{ github.run_number }}"
          echo "github.run_attempt: ${{ github.run_attempt }}"
          echo "github.actor: ${{ github.actor }}"
          echo "github.server_url: ${{ github.server_url }}"
          echo "github.api_url: ${{ github.api_url }}"

          echo "==== Git Information ===="
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.ref_protected: ${{ github.ref_protected }}"
          echo "github.sha: ${{ github.sha }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.event_path: ${{ github.event_path }}"
          echo "github.event contains complex data, checking event type: ${{ github.event.type || 'N/A' }}"

          echo "==== Action Information ===="
          echo "github.action: ${{ github.action }}"
          echo "github.action_path: ${{ github.action_path }}"
          echo "github.workspace: ${{ github.workspace }}"

      # Build
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: GitHub Pages 404 Workaround
        run: cd dist && cp index.html 404.html

      # Test
      # - name: Unit Tests
      #   run: npm run test:unit

      # Deploy
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
